// Math Constants
pi = 3.141592653589793280

// Color Constants
c_aqua = 16776960
c_black = 0
c_blue = 16711680
c_dkgray = 4210752
c_fuchsia = 16711935
c_gray = 8421504
c_green = 32768
c_lime = 65280
c_ltgray = 12632256
c_maroon = 128
c_navy = 8388608
c_olive = 32896
c_purple = 8388736
c_red = 255
c_silver = 12632256
c_teal = 8421376
c_white = 16777215
c_yellow = 65535
c_orange = 4235519

// Font Alignment Constants
fa_left = 0
fa_center = 1
fa_right = 2
fa_top = 0
fa_middle = 1
fa_bottom = 2

// Primitive Type Constants
pr_pointlist = 1
pr_linelist = 2
pr_linestrip = 3
pr_trianglelist = 4
pr_trianglestrip = 5
pr_trianglefan = 6

// Blend Mode Constants
bm_normal = 0
bm_add = 1
bm_max = 2
bm_subtract = 3
bm_zero = 1
bm_one = 2
bm_src_colour = 3
bm_inv_src_colour = 4
bm_src_color = 3
bm_inv_src_color = 4
bm_src_alpha = 5
bm_inv_src_alpha = 6
bm_dest_alpha = 7
bm_inv_dest_alpha = 8
bm_dest_colour = 9
bm_inv_dest_colour = 10
bm_dest_color = 9
bm_inv_dest_color = 10
bm_src_alpha_sat = 11
// Transform Mode Constants
tf_point = 0
tf_linear = 1
tf_anisotropic = 2
// Mipmapping Mode Constants
mip_off = 0
mip_on = 1
mip_markedonly = 2
// Comparison Function Constants
cmpfunc_never = 1
cmpfunc_less = 2
cmpfunc_equal = 3
cmpfunc_lessequal = 4
cmpfunc_greater = 5
cmpfunc_notequal = 6
cmpfunc_greaterequal = 7
cmpfunc_always = 8
// Backface Culling Constants
cull_noculling = 0
cull_clockwise = 1
cull_counterclockwise = 2
// Light Types
lighttype_dir = 0
lighttype_point = 1


// Rivals of Aether

// UI Element Types
UI_WIN_THEME = 0
UI_WIN_BG = 1
UI_WIN_PORTRAIT = 2
UI_WIN_SIDEBAR = 3
UI_HUD_ICON = 4
UI_HUDHURT_ICON = 5
UI_OFFSCREEN = 6
UI_CHARSELECT = 7

// CPU Action Types
CPU_STAND = 0
CPU_CROUCH = 1
CPU_JUMP = 2
CPU_RUN = 3
CPU_PARRY = 4
CPU_ROLL = 5
CPU_FIGHT = 6
CPU_EVADE = 7
CPU_CONTROL = 8

// Attack Directions
DIR_NONE = 0
DIR_SIDE = 1
DIR_FORWARD = 2
DIR_UP = 3
DIR_DOWN = 4
DIR_ANY = 5
DIR_LEFT = 6
DIR_RIGHT = 7
DIR_BACK = 8

// Character Info Types
INFO_HUD = 0
INFO_HUDHURT = 1
INFO_ICON = 2
INFO_PORTRAIT = 3
INFO_STR_NAME = 4
INFO_STR_AUTHOR = 5
INFO_OFFSCREEN = 6
INFO_CHARSELECT = 7
INFO_STR_DESCRIPTION = 8
INFO_VER_MAJOR = 9
INFO_VER_MINOR = 10
INFO_PLURAL = 11
INFO_SIDEBAR = 12

// Stage Data Types
SD_X_POS = 0
SD_Y_POS = 1
SD_TOP_BLASTZONE = 2
SD_BOTTOM_BLASTZONE = 3
SD_SIDE_BLASTZONE = 4
SD_WIDTH = 5
SD_ID = 6
SD_LEFT_BLASTZONE_X = 7
SD_RIGHT_BLASTZONE_X = 8
SD_TOP_BLASTZONE_Y = 9
SD_BOTTOM_BLASTZONE_Y = 10

// Attack Grid Indices
AG_CATEGORY = 0
AG_SPRITE = 1
AG_AIR_SPRITE = 13
AG_HURTBOX_SPRITE = 16
AG_HURTBOX_AIR_SPRITE = 19
AG_NUM_WINDOWS = 4
AG_HAS_LANDING_LAG = 7
AG_OFF_LEDGE = 8
AG_LANDING_LAG = 12
AG_STRONG_CHARGE_WINDOW = 10
AG_USES_CUSTOM_GRAVITY = 24
AG_NO_PARRY_STUN = 20

// Window Grid Indices
AG_WINDOW_TYPE = 1
AG_WINDOW_LENGTH = 2
AG_WINDOW_ANIM_FRAMES = 3
AG_WINDOW_ANIM_FRAME_START = 4
AG_WINDOW_HSPEED = 5
AG_WINDOW_VSPEED = 6
AG_WINDOW_HSPEED_TYPE = 7
AG_WINDOW_VSPEED_TYPE = 8
AG_WINDOW_HAS_CUSTOM_FRICTION = 9
AG_WINDOW_CUSTOM_AIR_FRICTION = 10
AG_WINDOW_CUSTOM_GROUND_FRICTION = 11
AG_WINDOW_CUSTOM_GRAVITY = 26
AG_WINDOW_HAS_WHIFFLAG = 12
AG_WINDOW_INVINCIBILITY = 13
AG_WINDOW_HITPAUSE_FRAME = 24
AG_WINDOW_CANCEL_TYPE = 31
AG_WINDOW_CANCEL_FRAME = 32
AG_WINDOW_HAS_SFX = 57
AG_WINDOW_SFX = 58
AG_WINDOW_SFX_FRAME = 59
AG_WINDOW_GOTO = 62

// Hitbox Grid Indices
HG_PARENT_HITBOX = 0
HG_HITBOX_TYPE = 1
HG_WINDOW = 2
HG_WINDOW_CREATION_FRAME = 3
HG_LIFETIME = 4
HG_HITBOX_X = 5
HG_HITBOX_Y = 6
HG_WIDTH = 7
HG_HEIGHT = 8
HG_SHAPE = 9
HG_PRIORITY = 10
HG_DAMAGE = 11
HG_ANGLE = 12
HG_BASE_KNOCKBACK = 13
HG_KNOCKBACK_SCALING = 14
HG_EFFECT = 15
HG_BASE_HITPAUSE = 16
HG_HITPAUSE_SCALING = 17
HG_VISUAL_EFFECT = 18
HG_VISUAL_EFFECT_X_OFFSET = 19
HG_VISUAL_EFFECT_Y_OFFSET = 20
HG_VISUAL_EFFECT_DISTANCE = 58
HG_HIT_SFX = 21
HG_ANGLE_FLIPPER = 22
HG_EXTRA_HITPAUSE = 23
HG_GROUNDEDNESS = 24
HG_EXTRA_CAMERA_SHAKE = 25
HG_IGNORES_PROJECTILES = 26
HG_HIT_LOCKOUT = 27
HG_EXTENDED_PARRY_STUN = 28
HG_HITBOX_GROUP = 29
HG_HITSTUN_MULTIPLIER = 30
HG_DRIFT_MULTIPLIER = 31
HG_SDI_MULTIPLIER = 32
HG_TECHABLE = 33
HG_FORCE_FLINCH = 34
HG_FINAL_BASE_KNOCKBACK = 35
HG_THROWS_ROCK = 36

HG_PROJECTILE_SPRITE = 37
HG_PROJECTILE_MASK = 38
HG_PROJECTILE_COLLISION_SPRITE = 56
HG_PROJECTILE_ANIM_SPEED = 39
HG_PROJECTILE_UNBASHABLE = 40
HG_PROJECTILE_HSPEED = 42
HG_PROJECTILE_VSPEED = 43
HG_PROJECTILE_GRAVITY = 44
HG_PROJECTILE_GROUND_FRICTION = 45
HG_PROJECTILE_AIR_FRICTION = 46
HG_PROJECTILE_WALL_BEHAVIOR = 47
HG_PROJECTILE_GROUND_BEHAVIOR = 48
HG_PROJECTILE_ENEMY_BEHAVIOR = 49
HG_PROJECTILE_LIFESPAN = 50
HG_PROJECTILE_PARRY_STUN = 51
HG_PROJECTILE_DOES_NOT_REFLECT = 52
HG_PROJECTILE_IS_TRANSCENDENT = 53
HG_PROJECTILE_DESTROY_EFFECT = 54
HG_PROJECTILE_PLASMA_SAFE = 55
HG_HIT_PARTICLE_NUM = 57

// States
PS_IDLE = 24
PS_IDLE_AIR = 1
PS_CROUCH = 32
PS_JUMPSQUAT = 28
PS_FIRST_JUMP = 3
PS_DOUBLE_JUMP = 2
PS_WALL_JUMP = 16
PS_LAND = 13
PS_WALK = 26
PS_WALK_TURN = 20
PS_DASH_START = 22
PS_DASH = 23
PS_DASH_STOP = 27
PS_DASH_TURN = 29
PS_WAVELAND = 21
PS_ATTACK_AIR = 5
PS_ATTACK_GROUND = 6
PS_LANDING_LAG = 19
PS_HITSTUN = 12
PS_HITSTUN_LAND = 7
PS_TUMBLE = 0
PS_PRATFALL = 10
PS_PRATLAND = 11
PS_AIR_DODGE = 8
PS_PARRY_START = 30
PS_PARRY = 9
PS_ROLL_BACKWARD = 33
PS_ROLL_FORWARD = 34
PS_TECH_GROUND = 31
PS_TECH_BACKWARD = 35
PS_TECH_FORWARD = 36
PS_WALL_TECH = 18
PS_SPAWN = 25
PS_RESPAWN = 14
PS_DEAD = 15
PS_WRAPPED = 37
PS_FROZEN = 38
PS_FLASHED = 39
PS_CRYSTALIZED = 40
PS_BURIED = 41

// State Categories
SC_HITSTUN = 4
SC_GROUND_NEUTRAL = 40
SC_GROUND_COMMITTED = 42
SC_AIR_NEUTRAL = 41
SC_AIR_COMMITTED = 43

// Attack Indices
AT_JAB = 1
AT_FTILT = 4
AT_DTILT = 5
AT_UTILT = 6
AT_FSTRONG = 7
AT_DSTRONG = 8
AT_USTRONG = 9
AT_DATTACK = 10
AT_FAIR = 11
AT_BAIR = 12
AT_DAIR = 13
AT_UAIR = 14
AT_NAIR = 15
AT_FSPECIAL = 16
AT_DSPECIAL = 17
AT_USPECIAL = 18
AT_NSPECIAL = 19
AT_TAUNT = 35
AT_FSTRONG_2 = 20
AT_DSTRONG_2 = 21
AT_USTRONG_2 = 22
AT_FTHROW = 26
AT_UTHROW = 27
AT_DTHROW = 28
AT_NTHROW = 29
AT_NSPECIAL_AIR = 41
AT_NSPECIAL_2 = 33
AT_FSPECIAL_AIR = 34
AT_FSPECIAL_2 = 25
AT_USPECIAL_GROUND = 23
AT_USPECIAL_2 = 24
AT_DSPECIAL_AIR = 32
AT_DSPECIAL_2 = 30
AT_TAUNT_2 = 36
AT_EXTRA_1 = 31
AT_EXTRA_2 = 37
AT_EXTRA_3 = 38
AT_EXTRA_4 = 39
AT_EXTRA_5 = 40

// Match Setting Types
SET_STOCKS = 0
SET_STONKS = 0
SET_TIMER = 1
SET_TEAMS = 2
SET_TEAMATTACK = 3
SET_HITBOX_VIS = 4
SET_SEASON = 5
SET_RUNES = 6
SET_PRACTICE = 7
SET_TURBO = 8
SET_SCALING = 9

// Local Setting Types
SET_ACCESSIBLE = 0
SET_HUD_SIZE = 1
SET_HUD_NAMES = 2
//SET_SFX_VOLUME = 3
//SET_MUSIC_VOLUME = 4
//SET_MENU_VOLUME = 5
SET_FX_QUALITY = 6
SET_HUD_SHAKE = 7
SET_RETRO_FX = 8
SET_LANGUAGE = 9

// BG Data Types
BG_LAYER_ANIMSPD = 0
BG_LAYER_X = 1
BG_LAYER_Y = 2
BG_LAYER_PARALLAX_X = 3
BG_LAYER_PARALLAX_Y = 4
BG_LAYER_REPEAT = 5
BG_LAYER_AUTOSCROLL_X = 6
BG_LAYER_AUTOSCROLL_Y = 7

// Object Indices
oPlayer = 3
oTestPlayer = 4
pHitBox = 6
pHurtBox = 5
hit_fx_obj = 167

obj_article1 = 56
obj_article2 = 57
obj_article3 = 58
obj_article_platform = 61
obj_article_solid = 60
//obj_article_parent = 55

obj_stage_article = 362
obj_stage_article_platform = 363
obj_stage_article_solid = 364
obj_stage_main = 367

// Character Indices
CH_ZETTERBURN = 2
CH_ORCANE = 3
CH_WRASTOR = 4
CH_KRAGG = 5
CH_FORSBURN = 6
CH_MAYPUL = 7
CH_ABSA = 8
CH_ETALUS = 9
CH_ORI = 10
CH_RANNO = 11
CH_CLAIREN = 12
CH_SYLVANOS = 13
CH_ELLIANA = 14
CH_SHOVEL_KNIGHT = 15
CH_MOLLO = 16
CH_HODAN = 17
CH_POMME = 18
CH_OLYMPIA = 19

//input indexes
PC_LEFT_HARD_PRESSED = 0
PC_RIGHT_HARD_PRESSED = 2
PC_UP_HARD_PRESSED = 4
PC_DOWN_HARD_PRESSED = 6
PC_LEFT_STRONG_PRESSED = 9
PC_RIGHT_STRONG_PRESSED = 11
PC_UP_STRONG_PRESSED = 13
PC_DOWN_STRONG_PRESSED = 15
PC_LEFT_STICK_PRESSED = 17
PC_RIGHT_STICK_PRESSED = 19
PC_UP_STICK_PRESSED = 21
PC_DOWN_STICK_PRESSED = 23
PC_JUMP_PRESSED = 25
PC_ATTACK_PRESSED = 27
PC_SHIELD_PRESSED = 29
PC_SPECIAL_PRESSED = 31
PC_STRONG_PRESSED = 33
PC_TAUNT_PRESSED = 35

// Hit Particle Types
PART_NORMAL = 2566
PART_ZET_FIRE = 2568
PART_ORC_LIGHT = 2582
PART_ORC_DARK = 2580
PART_WRA_WIND = 2584
PART_WRA_FEATHER = 2586
PART_KRA_ROCK = 2578
PART_FOR_SMOKE = 2576
PART_MAY_LEAF = 2572
PART_ABS_ZAP = 2574
PART_ETA_ICE = 2570
PART_ORI_ORANGE = 1530
PART_ORI_BLUE = 1531
PART_RAN_POISON = 2598
PART_CLA_RED = 2597
PART_CLA_BLUE = 2596
PART_SYL_FLOWER = 2599
PART_SYL_WOOD = 2600
PART_ELL_FIRE = 2749
PART_SHO_FIRE = 2662
PART_SHO_MUSIC = 2658

// Hit Effects
//general
HFX_GEN_OMNI = 301
HFX_GEN_SPIN = 302
HFX_GEN_DIR = 303
HFX_GEN_BIG = 304
HFX_GEN_SWEET = 305
//fors
HFX_FOR_HIT_BIG = 13
HFX_FOR_HIT_SMALL = 14
//zetter
HFX_ZET_FIRE = 3
HFX_ZET_FIRE_DIR = 4
HFX_ZET_FIRE_BIG = 148
HFX_ZET_SHINE_BG = 200
HFX_ZET_SHINE_FG = 201
HFX_ZET_SHINE_BIG_BG = 202
HFX_ZET_SHINE_BIG_FG = 203
HFX_ZET_METEOR_BREAK = 99
HFX_ZET_GROUNDFIRE_END = 100
//clairen
HFX_CLA_FSPEC_SPARK = 121
HFX_CLA_FSPEC_DASH = 122
HFX_CLA_PLASMA_X = 123
HFX_CLA_PLASMA_SLASH = 124
HFX_CLA_TIP_X = 125
HFX_CLA_TIP_PLUS = 126
HFX_CLA_TIP_BIG = 127
HFX_CLA_PLASMA_PLUS = 128
HFX_CLA_PLASMA_X_BIG = 129
HFX_CLA_PLUS_BIG = 130
HFX_CLA_DSMASH_BREAK = 256
HFX_CLA_FSMASH_BREAK = 257
HFX_CLA_SHINE = 255
//orcane
HFX_ORC_WATER_DARK = 5
HFX_ORC_WATER_LIGHT = 6
HFX_ORC_WATER = 7
HFX_ORC_WATER_SIDE_DARK = 8
HFX_ORC_WATER_SIDE_LIGHT = 9
HFX_ORC_WATER_SIDE = 10
HFX_ORC_WATER_DOWN_LIGHT = 101
HFX_ORC_WATER_BIG_DARK = 149
HFX_ORC_WATER_BIG_LIGHT = 150
HFX_ORC_WATER_BIG = 195
HFX_ORC_WATER_HUGE = 161
//etalus
HFX_ETA_ICE_BIG = 199
HFX_ETA_ICE_HUGE = 158
HFX_ETA_SHARD_LONG = 25
HFX_ETA_SHARD_MED = 26
HFX_ETA_ICE_SMALL = 27
HFX_ETA_ICEPOP_BIG = 28
HFX_ETA_ICEPOP_SMALL = 29
HFX_ETA_TILE_MELT = 103
HFX_ETA_FSPEC_BREAK = 102
//ori
HFX_ORI_AURA = 105
HFX_ORI_SEIN_AURA = 106
HFX_ORI_SEIN_SHOT = 107
HFX_ORI_SEIN_HIT = 108
HFX_ORI_ORANGE_SMALL = 109
HFX_ORI_ORANGE_BIG = 110
HFX_ORI_BLUE_SMALL = 111
HFX_ORI_BLUE_BIG = 112
HFX_ORI_BASH_START = 113
HFX_ORI_BASH_ARROW = 104
HFX_ORI_CHARGE = 114
HFX_ORI_FSPEC_BOOM = 115
//wrastor
HFX_WRA_WIND_SMALL = 194
HFX_WRA_WIND_BIG = 196
HFX_WRA_WIND_HUGE = 156
HFX_WRA_WING_SMALL = 11
HFX_WRA_WING_SMALL_UP = 12
HFX_WRA_WING_BIG = 146
HFX_WRA_WING_BIG_UP = 147
//ranno
HFX_RAN_POISON_SMALL = 116
HFX_RAN_POISON_MED = 117
HFX_RAN_POISON_SWEET = 118
HFX_RAN_POISON_BIG = 119
HFX_RAN_POISON_HUGE = 160
HFX_RAN_DSMASH_SWEET = 120
//maypul
HFX_MAY_SEED_BREAK = 15
HFX_MAY_SEED_HIT = 16
HFX_MAY_LEAF_BIG = 17
HFX_MAY_LEAF_SMALL = 18
HFX_MAY_WHIP = 198
HFX_MAY_LEAF_HUGE = 159
HFX_MAY_LEAF_DASH = 70
//elli
HFX_ELL_NSPEC_FIRE = 138
HFX_ELL_FSPEC_BREAK = 139
HFX_ELL_NSPEC_BREAK = 140
HFX_ELL_FSPEC_HIT = 141
HFX_ELL_BOOM_HIT = 142
HFX_ELL_BOOM_BIG = 143
HFX_ELL_STEAM_HIT = 144
HFX_ELL_BOOM_RED = 145
HFX_ELL_FSPEC_BIG_HIT = 163
HFX_ELL_FSPEC_BIG_MISS = 164
//sylvanos
HFX_SYL_PETAL_BIG = 131
HFX_SYL_PETAL_SMALL = 132
HFX_SYL_PETAL_SWEET = 133
HFX_SYL_WOOD_BIG = 134
HFX_SYL_WOOD_SMALL = 135
HFX_SYL_WOOD_HUGE = 162
//ragnir
HFX_MAY_RAG_WHIP = 204
HFX_MAY_RAG_SEED_BREAK = 136
HFX_MAY_RAG_SEED_HIT = 137
//shovel knight
HFX_SHO_SWEET = 306
HFX_SHO_SAW_BREAK = 151
HFX_SHO_GHOST_BREAK = 152
HFX_SHO_GEAR_BREAK = 153
HFX_SHO_BLOCK_BREAK = 154
HFX_SHO_COIN_CAPTURE = 250
HFX_SHO_FLARE_ROD = 251
HFX_SHO_FLAME_SMALL = 252
HFX_SHO_FLAME_BIG = 253
HFX_SHO_HORN_HIT = 254
HFX_SHO_BOOM_BAIT = 249
//absa
HFX_ABS_SWEET = 19
HFX_ABS_ZAP_SMALL = 20
HFX_ABS_ZAP_BIG = 21
HFX_ABS_ZAP_DIR = 22
HFX_ABS_SWEET_BIG = 197
HFX_ABS_ZAP_HUGE = 157
//kragg
HFX_KRA_ROCK_BIG = 192
HFX_KRA_ROCK_SMALL = 193
HFX_KRA_ROCK_HUGE = 155
//abyss
HFX_ABY_EXPLODE_WARN = 66
HFX_ABY_PROJ_HIT = 67
HFX_ABY_FLOOR_HIT = 68
//mollo
HFX_MOL_POP = 259
HFX_MOL_BOOM_NORM = 260
HFX_MOL_BOOM_FLASH = 262
HFX_MOL_BOOM_FINISH = 263
HFX_MOL_BOOM_CRACK_UP = 266
HFX_MOL_BOOM_CRACK = 261
HFX_MOL_BOOM_FLARE = 264
HFX_MOL_BOOM_SPARKLE = 265
HFX_MOL_BAT_TOSS = 267
HFX_MOL_SMOKE_BOMB = 268
HFX_MOL_PAINT_HIT = 269
HFX_MOL_EXPLODE_HIT = 270
HFX_MOL_BOOM_FINISH_FRONT = 271
//hodan
HFX_HOD_SPLASH = 280
HFX_HOD_WHIRL_POP = 281
HFX_HOD_STEAM_BIG = 282
HFX_HOD_STEAM_HUGE = 294
HFX_HOD_USPEC_UNCHARGE = 283
HFX_HOD_USPEC_CHARGE = 284
HFX_HOD_DSMASH_POP = 285
HFX_HOD_FAIR_END_BG = 288
HFX_HOD_FAIR_END = 289
HFX_HOD_NSPEC_END = 290
HFX_HOD_MUD_WAVE = 287
HFX_HOD_MUD_SLAM = 291
HFX_HOD_MUD_HIT = 292
HFX_HOD_MUD_BREAK = 293
//olympia
HFX_OLY_SPARKLE = 310
HFX_OLY_SHINE_SMALL = 311
HFX_OLY_GEM_SHINE = 312
HFX_OLY_CRYSTALIZE_START = 313
HFX_OLY_CRYSTALIZE_END = 314
HFX_OLY_CRYSTAL_SMALL = 315
HFX_OLY_CRYSTAL_BIG = 316
//pomme
HFX_POM_NOTE_FALLOFF = 323
HFX_POM_BIG = 322
HFX_POM_MUSIC = 321
HFX_POM_YELL = 320
HFX_POM_YELL_BIG = 319